apiVersion: v1
kind: Pod
metadata:
  name: teste-nginx
  labels:
    app: app-web
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    resources:
      requests:
        cpu: "500m"
      limits:
        memory: "64Mi"
        cpu: "500"
---
apiVersion: v1
kind: Service
metadata:
  name: teste-servico
spec:
  type: NodePort
  selector:
    app: app-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30123